sudo: false
language: node_js
addons:
  sauce_connect: true
node_js:
- 0.1

script:
- make test-travisci

env:
  global:
  - secure: h4eLQ2jkR1p2O5BEyscLtbNT/84LDGFnj977SeKmg3flVTpRR+ZiYb5YvIUIYfnwsw1jlr11xv0cya23nJjJA5DQjrVS1/kg4sWrLD9Gs6TTqpSNSk0HrFpxhrHZ/uSSPfV9fbyxfDLxgq72fc55WCuY5Osy1kXmsPdJX79/cOU=
  - secure: GXrMWPVtgAG4ICawbVdzh3R+Q+tHwYT1FcgtFbn4w7s6NZUKRdDodBM0yuDZA8pxqhQvSj/HlLjkNQI4G1wPhkHESlMWzrH5737eaJ1PHQvYV/XEnpjawQXYTOg3OYEx07mHGm+mqbAaDDHulgkeI5J4NXFMQO+JG7eYTqpotXE=
  - SAUCE_CONNECT_READY_FILE=/tmp/sauce-connect-ready
  - LOGS_DIR=/tmp/chai-build/logs

deploy:
  provider: npm
  email:
    secure: "M9J56tqJwOxn6D3PSh8BNGac/8XjTCRGCFexN5QFl7Ha9AKnyQTy1ZAaJonMGoClBhh37Dy/89wVWmqg4NPckrD5Ej7NvwhTjVfEHusllaCROqVu5m7ijS3WKlIxM/xtBzU7SqRY41JxloP+CLKxRiKRWQJDvgwUZW7OHdmAkAY="
  api_key:
    secure: ihzLWemQDFmsF4iQ3sS5/Wt0GQy6v15WgsxYfocpLuYWjxaAWgB4vQ3gUar8UpnE7lEFtNUOTIkPob0MSgNrFjoH2PB1sh5cW/acDE7kF7Z7hVxr8zGWkgiWXeNd08lz1mruizK1L/I0o2k/7o7zEDzShpsYSwgWfekzbJxLtC8=
  on:
    tags: true
    repo: chaijs/chai
    all_branches: true
